CREATE DATABASE SmartHomeDB;
GO

USE SmartHomeDB;
GO

CREATE TABLE USUARIO (
    correo NVARCHAR(100) PRIMARY KEY NOT NULL,
    nombres NVARCHAR(50) NOT NULL,
    apellidos NVARCHAR(150) NOT NULL,
    contrasena NVARCHAR(225) NOT NULL,
    es_activo BIT NOT NULL
);
GO

CREATE TABLE VIVIENDA (
    id_vivienda INT IDENTITY(1,1) PRIMARY KEY,
    direccion NVARCHAR(100) NOT NULL,
    codigo_postal NVARCHAR(10) NOT NULL
);
GO

CREATE TABLE TIPO_DISPOSITIVO (
    id_tipo INT IDENTITY(1,1) PRIMARY KEY,
    nombre NVARCHAR(50) NOT NULL UNIQUE
);
GO

CREATE TABLE UBICACION (
    id_ubicacion INT IDENTITY(1,1) PRIMARY KEY,
    nombre NVARCHAR(50) NOT NULL,
    id_vivienda INT NOT NULL,
    CONSTRAINT FK_UBICACION_VIVIENDA FOREIGN KEY (id_vivienda) REFERENCES VIVIENDA(id_vivienda)
);
GO

CREATE TABLE USUARIO_VIVIENDA (
    correo NVARCHAR(100) NOT NULL,
    id_vivienda INT NOT NULL,
    rol NVARCHAR(20) NOT NULL CHECK (rol IN (N'Admin', N'Estandar')),
    CONSTRAINT PK_USUARIO_VIVIENDA PRIMARY KEY (correo, id_vivienda),
    CONSTRAINT FK_USUARIO_VIVIENDA_USUARIO FOREIGN KEY (correo) REFERENCES USUARIO(correo),
    CONSTRAINT FK_USUARIO_VIVIENDA_VIVIENDA FOREIGN KEY (id_vivienda) REFERENCES VIVIENDA(id_vivienda)
);
GO

CREATE TABLE DISPOSITIVO (
    id_dispositivo INT IDENTITY(1,1) PRIMARY KEY,
    nombre NVARCHAR(50) NOT NULL,
    estado BIT NOT NULL,
    fecha_hora DATETIME2 NOT NULL,
    id_tipo INT NOT NULL,
    id_ubicacion INT NOT NULL,
    CONSTRAINT FK_DISPOSITIVO_TIPO FOREIGN KEY (id_tipo) REFERENCES TIPO_DISPOSITIVO(id_tipo),
    CONSTRAINT FK_DISPOSITIVO_UBICACION FOREIGN KEY (id_ubicacion) REFERENCES UBICACION(id_ubicacion)
);
GO

CREATE TABLE ACCION (
    id_accion INT IDENTITY(1,1) PRIMARY KEY,
    nombre NVARCHAR(50) NOT NULL,
    id_tipo INT NOT NULL,
    CONSTRAINT FK_ACCION_TIPO FOREIGN KEY (id_tipo) REFERENCES TIPO_DISPOSITIVO(id_tipo)
);
GO

CREATE TABLE CONFIGURACION_DISPOSITIVO (
    id_configuracion INT IDENTITY(1,1) PRIMARY KEY,
    id_dispositivo INT NOT NULL,
    atributo NVARCHAR(50) NOT NULL,
    valor NVARCHAR(50) NOT NULL,
    CONSTRAINT FK_CONFIG_DISPOSITIVO FOREIGN KEY (id_dispositivo) REFERENCES DISPOSITIVO(id_dispositivo)
);
GO

CREATE TABLE AUTOMATIZACIONES (
    id_automatizacion INT IDENTITY(1,1) PRIMARY KEY,
    nombre NVARCHAR(100) NOT NULL,
    id_vivienda INT NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    activa BIT NOT NULL,
    CONSTRAINT FK_AUTOMATIZACIONES_VIVIENDA FOREIGN KEY (id_vivienda) REFERENCES VIVIENDA(id_vivienda)
);
GO

CREATE TABLE AUTOMATIZACION_OBJETIVO (
    id_automatizacion INT NOT NULL,
    id_tipo INT NOT NULL,
    id_ubicacion INT NOT NULL,
    CONSTRAINT PK_AUTOMATIZACION_OBJETIVO PRIMARY KEY (id_automatizacion, id_tipo, id_ubicacion),
    CONSTRAINT FK_AUTO_OBJ_AUTOMATIZACION FOREIGN KEY (id_automatizacion) REFERENCES AUTOMATIZACIONES(id_automatizacion),
    CONSTRAINT FK_AUTO_OBJ_TIPO FOREIGN KEY (id_tipo) REFERENCES TIPO_DISPOSITIVO(id_tipo),
    CONSTRAINT FK_AUTO_OBJ_UBICACION FOREIGN KEY (id_ubicacion) REFERENCES UBICACION(id_ubicacion)
);
GO